name: Android Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool pkg-config autoconf automake build-essential libssl-dev libffi-dev libgmp-dev zlib1g-dev libncurses5-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libdb-dev libpcap-dev xz-utils libexpat1-dev liblzma-dev libffi-dev python3-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes y | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-game-apk
          path: bin/*.apk
